apiVersion: v1
kind: Secret
metadata:
  name: smartlift-backend-secrets
  namespace: smartlift
type: Opaque
stringData:
  DB_PASSWORD: change-me
  JWT_SECRET: change-me-base64-or-random-secret
  MAIL_HOST: ""
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
