services:
  postgres:
    image: postgres:17-alpine
    container_name: smartlift-db
    environment:
      POSTGRES_DB: smartlift
      POSTGRES_USER: smartlift
      POSTGRES_PASSWORD: smartlift
    ports:
      - "5432:5432"
    volumes:
      - smartlift-data:/var/lib/postgresql/data

volumes:
  smartlift-data:
