services:
  postgres:
    image: postgres:17-alpine
    container_name: smartlift-db
    environment:
      POSTGRES_DB: smartlift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5433:5432"
    volumes:
      - smartlift-data:/var/lib/postgresql/data

volumes:
  smartlift-data: